export const GET_SAMPLE = "GET_SAMPLE";
export const SAMPLE_ERROR = "SAMPLE_ERROR";

export const HIDDE_REGISTER_FORM = "HIDDE_REGISTER_FORM";
export const SHOW_REGISTER_FORM = "SHOW_REGISTER_FORM";
export const SHOW_LOGIN_FORM = "SHOW_LOGIN_FORM";
export const HIDDE_LOGIN_FORM = "HIDDE_LOGIN_FORM";
export const SHOW_FORM = "SHOW_FORM";
export const SHOW_RECOVER_PASSWORD = "SHOW_RECOVER_PASSWORD";
export const HIDDE_RECOVER_PASSWORD = "HIDDE_RECOVER_PASSWORD";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const USER_SUCCESS = "USER_SUCCESS";

export const GET_ROOM_SUCCESS = "GET_ROOM_SUCCESS";
export const GET_ROOM_ERROR = "GET_ROOM_ERROR";

export const UPLOAD_ROOM_SUCCESS = "UPLOAD_ROOM_SUCCESS";
export const IS_UPLOADING_ROOM = "IS_UPLOADING_ROOM";
export const SET_UPLOADING_PERCENTAGE = "SET_UPLOADING_PERCENTAGE";

export const ROOM_DETAIL_SUCCESS = "ROOM_DETAIL_SUCCESS";
export const RESET_INITIAL_STATE = "RESET_INITIAL_STATE";
