export const GET_SAMPLE = "GET_SAMPLE";
export const SAMPLE_ERROR = "SAMPLE_ERROR";

export const HIDDE_REGISTER_FORM = "HIDDE_REGISTER_FORM";
export const SHOW_REGISTER_FORM = "SHOW_REGISTER_FORM";
export const SHOW_LOGIN_FORM = "SHOW_LOGIN_FORM";
export const HIDDE_LOGIN_FORM = "HIDDE_LOGIN_FORM";
export const SHOW_FORM = "SHOW_FORM";
export const SHOW_PROMO = "SHOW_PROMO";
export const SHOW_RECOVER_PASSWORD = "SHOW_RECOVER_PASSWORD";
export const HIDDE_RECOVER_PASSWORD = "HIDDE_RECOVER_PASSWORD";
export const SHOW_BOOKINGADMIN = "SHOW_BOOKINGADMIN";
export const SHOW_BOOKING_DATA = "SHOW_BOOKING_DATA";
export const SHOW_TEXTAREA_DATA = "SHOW_TEXTAREA_DATA";
export const SHOW_ROOMPICK_UPLOAD = "SHOW_ROOMPICK_UPLOAD";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const USER_SUCCESS = "USER_SUCCESS";

export const UPLOAD_ROOM_SUCCESS = "UPLOAD_ROOM_SUCCESS";
export const IS_UPLOADING_ROOM = "IS_UPLOADING_ROOM";
export const SET_UPLOADING_PERCENTAGE = "SET_UPLOADING_PERCENTAGE";
export const UPLOAD_BOOKING_DATA = "UPLOAD_BOOKING_DATA";

export const ROOM_DETAIL_SUCCESS = "ROOM_DETAIL_SUCCESS";
export const RESET_INITIAL_STATE = "RESET_INITIAL_STATE";

export const DATE_DETAIL_SUCCESS = "DATE_DETAIL_SUCCESS";
export const DATE_CHARGE_SUCCESS = "DATE_CHARGE_SUCCESS";
